//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncBooking.Maximojo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://htng.org/2013A", ConfigurationName="Maximojo.IServer")]
    public interface IServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2013A/IServer/Post", ReplyAction="http://htng.org/2013A/IServer/PostResponse")]
        System.IO.Stream Post(System.IO.Stream message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2013A/IServer/Post", ReplyAction="http://htng.org/2013A/IServer/PostResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> PostAsync(System.IO.Stream message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerChannel : SyncBooking.Maximojo.IServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerClient : System.ServiceModel.ClientBase<SyncBooking.Maximojo.IServer>, SyncBooking.Maximojo.IServer {
        
        public ServerClient() {
        }
        
        public ServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream Post(System.IO.Stream message) {
            return base.Channel.Post(message);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> PostAsync(System.IO.Stream message) {
            return base.Channel.PostAsync(message);
        }
    }
}
