//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicabilityM
    {
        public tblApplicabilityM()
        {
            this.tblPropertyWeekendBiddingMaps = new HashSet<tblPropertyWeekendBiddingMap>();
            this.tblPropertyWeekendBiddingMaps1 = new HashSet<tblPropertyWeekendBiddingMap>();
            this.tblPropertyWeekendBiddingMapCorps = new HashSet<tblPropertyWeekendBiddingMapCorp>();
            this.tblPropertyWeekendBiddingMapCorps1 = new HashSet<tblPropertyWeekendBiddingMapCorp>();
            this.tblPropertyLeadTimeBiddingMaps = new HashSet<tblPropertyLeadTimeBiddingMap>();
            this.tblPropertyLeadTimeBiddingMaps1 = new HashSet<tblPropertyLeadTimeBiddingMap>();
            this.tblPropertyLeadTimeBiddingMapCorps = new HashSet<tblPropertyLeadTimeBiddingMapCorp>();
            this.tblPropertyLeadTimeBiddingMapCorps1 = new HashSet<tblPropertyLeadTimeBiddingMapCorp>();
            this.tblPropertyLOSBiddingMaps = new HashSet<tblPropertyLOSBiddingMap>();
            this.tblPropertyLOSBiddingMaps1 = new HashSet<tblPropertyLOSBiddingMap>();
            this.tblPropertyLOSBiddingMapCorps = new HashSet<tblPropertyLOSBiddingMapCorp>();
            this.tblPropertyLOSBiddingMapCorps1 = new HashSet<tblPropertyLOSBiddingMapCorp>();
            this.tblPropertyRoomsBiddingMaps = new HashSet<tblPropertyRoomsBiddingMap>();
            this.tblPropertyRoomsBiddingMaps1 = new HashSet<tblPropertyRoomsBiddingMap>();
            this.tblPropertyRoomsBiddingMapCorps = new HashSet<tblPropertyRoomsBiddingMapCorp>();
            this.tblPropertyRoomsBiddingMapCorps1 = new HashSet<tblPropertyRoomsBiddingMapCorp>();
        }
    
        public short iApplicabilityId { get; set; }
        public string sApplicability { get; set; }
        public Nullable<short> iSortOrder { get; set; }
    
        public virtual ICollection<tblPropertyWeekendBiddingMap> tblPropertyWeekendBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyWeekendBiddingMap> tblPropertyWeekendBiddingMaps1 { get; set; }
        public virtual ICollection<tblPropertyWeekendBiddingMapCorp> tblPropertyWeekendBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyWeekendBiddingMapCorp> tblPropertyWeekendBiddingMapCorps1 { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMap> tblPropertyLeadTimeBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMap> tblPropertyLeadTimeBiddingMaps1 { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMapCorp> tblPropertyLeadTimeBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMapCorp> tblPropertyLeadTimeBiddingMapCorps1 { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMap> tblPropertyLOSBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMap> tblPropertyLOSBiddingMaps1 { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMapCorp> tblPropertyLOSBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMapCorp> tblPropertyLOSBiddingMapCorps1 { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMap> tblPropertyRoomsBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMap> tblPropertyRoomsBiddingMaps1 { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMapCorp> tblPropertyRoomsBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMapCorp> tblPropertyRoomsBiddingMapCorps1 { get; set; }
    }
}
