//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdditionalCommision
    {
        public int iAdditionalCommisionId { get; set; }
        public Nullable<System.DateTime> dtCommisionStartDate { get; set; }
        public Nullable<System.DateTime> dtCommisionEndDate { get; set; }
        public Nullable<decimal> dCommission { get; set; }
        public Nullable<int> iPropId { get; set; }
        public bool bActive { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblPropertyM tblPropertyM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
