//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIDRoomAdultsTx
    {
        public long iBookingId { get; set; }
        public short iRoomNo { get; set; }
        public Nullable<short> iAdults { get; set; }
        public Nullable<short> iChildren { get; set; }
        public string sChildAge { get; set; }
    }
}
