//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingCancellationPolicyAmendMap
    {
        public long iID { get; set; }
        public long iAmendId { get; set; }
        public Nullable<long> iBookingDetailsID { get; set; }
        public string sPolicyName { get; set; }
        public System.DateTime dtDate { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        public virtual tblBookingAmedTx tblBookingAmedTx { get; set; }
    }
}
