//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBannerM
    {
        public int iBannerId { get; set; }
        public string sBannerName { get; set; }
        public string sBannerType { get; set; }
        public string sTextPosition { get; set; }
        public string sDescription { get; set; }
        public string cstatus { get; set; }
        public string sLinkId { get; set; }
        public string sImgUrl { get; set; }
        public Nullable<short> iResolutionW { get; set; }
        public Nullable<short> iResolutionH { get; set; }
        public string UniqueAzureFileName { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    }
}
