//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasicPropertyInfoTGSearch_Tmp
    {
        public long iId { get; set; }
        public string sSessionId { get; set; }
        public string sHotelCode { get; set; }
        public string sCurrencyCode { get; set; }
        public string sStopCell { get; set; }
        public string sLowestRatePlanCode { get; set; }
        public Nullable<int> iRank { get; set; }
        public string sHotelType { get; set; }
        public string iReviewRating { get; set; }
        public string iReviewCount { get; set; }
        public string sOverviewUrl { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
