//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingTripAdvisorReviewTx
    {
        public long iBookingId { get; set; }
        public Nullable<int> iPropId { get; set; }
        public string sMobile { get; set; }
        public string sCustomerName { get; set; }
        public string sCustomerEmail { get; set; }
        public Nullable<System.DateTime> dtReviewEmailDate { get; set; }
        public Nullable<bool> bIsReviewLinkClicked { get; set; }
        public Nullable<System.DateTime> dtReviewLinkClicked { get; set; }
        public Nullable<short> iEmailSentCount { get; set; }
    }
}
