//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidSettingsM
    {
        public decimal dMinBidAmountForCustomerAllowed { get; set; }
        public decimal dMinBidAmountDiffPer { get; set; }
        public decimal dMaxBidAmountDiffPer { get; set; }
        public decimal dOFRServiceCharge { get; set; }
        public decimal dOFRMinTotalEarning { get; set; }
    }
}
