//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankDetailM_log
    {
        public int iPropId { get; set; }
        public string sBankAccountNo { get; set; }
        public string sBaneficiariesName { get; set; }
        public string sBankName { get; set; }
        public string sBranchName { get; set; }
        public string sBranchAddress { get; set; }
        public string sMicrCode { get; set; }
        public string sIfscCode { get; set; }
        public string sLetterhead_BankAccount { get; set; }
        public string sCancelledCheque { get; set; }
        public string sPanCard { get; set; }
        public Nullable<decimal> dCommission { get; set; }
        public string sFName { get; set; }
        public string sFPhoneNo { get; set; }
        public string sFFaxNo { get; set; }
        public string sFEmailId { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtModifyDate { get; set; }
        public Nullable<int> iModifyBy { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
        public string sGstinNumber { get; set; }
        public string sRegisteredEntityName { get; set; }
        public string sPanNumber { get; set; }
        public Nullable<int> iStateId { get; set; }
        public string sEntityType { get; set; }
    }
}
