//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingGuestMap
    {
        public long iBookingGuestId { get; set; }
        public Nullable<long> iBookingDetailsID { get; set; }
        public string sGuestName { get; set; }
        public string sGuestEmail { get; set; }
        public string sGuestMobile { get; set; }
        public string sBedPreference { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<bool> bIsPrimary { get; set; }
        public string sCountryPhoneCode { get; set; }
    
        public virtual tblBookingDetailsTx tblBookingDetailsTx { get; set; }
    }
}
