//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasicPropertyInfoTGSpecific_Tmp
    {
        public long iId { get; set; }
        public string sSessionId { get; set; }
        public string sHotelCode { get; set; }
        public string sHotelName { get; set; }
        public string sCurrencyCode { get; set; }
        public string sLatitude { get; set; }
        public string sLongitude { get; set; }
        public string sAddress { get; set; }
        public string sCity { get; set; }
        public string sPostalCode { get; set; }
        public string sStateName { get; set; }
        public string sCountryName { get; set; }
        public string sAwardRating { get; set; }
        public string sStopCell { get; set; }
        public string sLowestRatePlanCode { get; set; }
        public string sFlexibleCheckIn { get; set; }
        public string sStateSeoId { get; set; }
        public string sCitySeoId { get; set; }
        public Nullable<int> iNoOfRooms { get; set; }
        public Nullable<int> iNoOfFloors { get; set; }
        public string sHotelType { get; set; }
        public string sDescription { get; set; }
        public string sCheckInTime { get; set; }
        public string sCheckOutTime { get; set; }
        public string sAreaSeoId { get; set; }
        public string sArea { get; set; }
        public string sAmenityDescription { get; set; }
        public string sReviewImageUrl { get; set; }
        public string sThumbnailUrl { get; set; }
        public string sThumbnailImageName { get; set; }
        public string sImageUrl { get; set; }
        public string sOverviewUrl { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
