//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookedDayWiseSeparateTaxAmountDetail
    {
        public int iBookingID { get; set; }
        public int iBookingDetailsID { get; set; }
        public System.DateTime dtStayDay { get; set; }
        public Nullable<decimal> dAmount { get; set; }
        public Nullable<decimal> dTaxPerc { get; set; }
        public Nullable<decimal> dTaxVal { get; set; }
        public int iTaxId { get; set; }
    }
}
