//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookedBidAmenity
    {
        public long iBookingId { get; set; }
        public string sAmenity { get; set; }
        public string sApplicability { get; set; }
        public string sType { get; set; }
        public byte iNo { get; set; }
    
        public virtual tblBookingTx tblBookingTx { get; set; }
    }
}
