//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateCompanyM
    {
        public tblCorporateCompanyM()
        {
            this.tblCorporateDomainMaps = new HashSet<tblCorporateDomainMap>();
        }
    
        public int iCompanyId { get; set; }
        public string sCompanyName { get; set; }
        public string sPrimaryContact { get; set; }
        public string sTelephoneNumber { get; set; }
        public string sEmailAddress { get; set; }
        public string sMobileNumber { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string cStatus { get; set; }
        public string sCountryCode { get; set; }
        public string sGstinNumber { get; set; }
        public string sRegisteredEntityName { get; set; }
        public Nullable<int> iCountryId { get; set; }
        public Nullable<int> iStateId { get; set; }
        public Nullable<int> iCityId { get; set; }
        public string sEntityType { get; set; }
        public Nullable<int> sPINCode { get; set; }
        public string sAddress { get; set; }
    
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblCorporateDomainMap> tblCorporateDomainMaps { get; set; }
    }
}
