//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerLoyaltyBookingsMap
    {
        public long iCustomerId { get; set; }
        public long iBookingId { get; set; }
        public string cStatus { get; set; }
    
        public virtual tblBookingTx tblBookingTx { get; set; }
        public virtual tblWebsiteUserMater tblWebsiteUserMater { get; set; }
    }
}
