//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConserveCommissionM
    {
        public int iCCId { get; set; }
        public Nullable<decimal> dCommission { get; set; }
        public Nullable<System.DateTime> dtFrom { get; set; }
        public Nullable<System.DateTime> dtTo { get; set; }
        public Nullable<bool> bDisplayRateComm { get; set; }
        public Nullable<bool> bCOComm { get; set; }
        public Nullable<decimal> dCounterTrigger { get; set; }
        public Nullable<bool> bBidComm { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string cStatus { get; set; }
    }
}
