//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerPointsMap
    {
        public long iId { get; set; }
        public long iCustomerId { get; set; }
        public Nullable<int> iTotalPoints { get; set; }
        public Nullable<int> iUsedPoints { get; set; }
        public Nullable<int> iRemPoints { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtExpiryOriginal { get; set; }
        public Nullable<System.DateTime> dtExpiry { get; set; }
        public string cType { get; set; }
        public string cStatus { get; set; }
    
        public virtual tblWebsiteUserMater tblWebsiteUserMater { get; set; }
    }
}
