//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountryCodePhoneM
    {
        public int iId { get; set; }
        public string sCountry { get; set; }
        public string sCode { get; set; }
        public string sFrontendCode { get; set; }
    }
}
