//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateDiscountLinkingTx
    {
        public int iPropId { get; set; }
        public System.DateTime dtDate { get; set; }
        public string sType { get; set; }
        public Nullable<decimal> dDisc { get; set; }
        public Nullable<int> iRateInclusion1 { get; set; }
        public Nullable<int> iApplicability1 { get; set; }
        public Nullable<int> iRateInclusion2 { get; set; }
        public Nullable<int> iApplicability2 { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    }
}
