//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrencyM
    {
        public tblCurrencyM()
        {
            this.tblPropertyMs = new HashSet<tblPropertyM>();
        }
    
        public short iCurrencyId { get; set; }
        public string sCurrencyCode { get; set; }
        public string sCurrency { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sImg { get; set; }
        public string sSymbol { get; set; }
        public string sCountryCurrencyCode { get; set; }
    
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblPropertyM> tblPropertyMs { get; set; }
    }
}
