//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerM
    {
        public int iCustomerId { get; set; }
        public string sUserName { get; set; }
        public string sPassword { get; set; }
        public string sGoogleToken { get; set; }
        public string sFacebookToken { get; set; }
        public Nullable<bool> bForceChangePass { get; set; }
        public string sName { get; set; }
        public string sEmail { get; set; }
        public string sPhone { get; set; }
        public Nullable<System.DateTime> dtLastModifyDate { get; set; }
        public Nullable<bool> bIsUnsubscribed { get; set; }
        public Nullable<int> iUpdatedBy { get; set; }
        public Nullable<bool> bIsBlocked { get; set; }
        public Nullable<int> BlockActionBy { get; set; }
        public Nullable<System.DateTime> dtBlockdate { get; set; }
        public string sBlockReason { get; set; }
    }
}
