//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityM
    {
        public tblCityM()
        {
            this.tblLocalityMs = new HashSet<tblLocalityM>();
        }
    
        public int iCityId { get; set; }
        public int iCountryId { get; set; }
        public int iStateId { get; set; }
        public string sCity { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblCountryM tblCountryM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual tblStateM tblStateM { get; set; }
        public virtual ICollection<tblLocalityM> tblLocalityMs { get; set; }
    }
}
