//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashBoardLeadPercComp
    {
        public int iPropId { get; set; }
        public Nullable<int> C0_1 { get; set; }
        public Nullable<int> C2_3 { get; set; }
        public Nullable<int> C4_7 { get; set; }
        public Nullable<int> C8_15 { get; set; }
        public Nullable<int> C16_30 { get; set; }
        public Nullable<int> C31_60 { get; set; }
        public Nullable<int> C61_90 { get; set; }
        public Nullable<int> C90_ { get; set; }
        public string cType { get; set; }
        public int Days { get; set; }
    }
}
