//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashBoardWeekRevenueValueComp
    {
        public int iPropId { get; set; }
        public Nullable<int> Mon { get; set; }
        public Nullable<int> Tue { get; set; }
        public Nullable<int> Wed { get; set; }
        public Nullable<int> Thur { get; set; }
        public Nullable<int> Fri { get; set; }
        public Nullable<int> Sat { get; set; }
        public Nullable<int> Sun { get; set; }
        public string cType { get; set; }
        public int Days { get; set; }
    }
}
