//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashBoardPerformanceRate
    {
        public int iPropId { get; set; }
        public string sType { get; set; }
        public Nullable<int> Bid { get; set; }
        public Nullable<int> Negotiate { get; set; }
        public Nullable<int> Buy { get; set; }
        public Nullable<int> Corporate { get; set; }
        public Nullable<int> OverAll { get; set; }
        public int Days { get; set; }
    }
}
