//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDaywiseBookingRateTx
    {
        public long iBookingDetailsID { get; set; }
        public System.DateTime dtStayDate { get; set; }
        public Nullable<decimal> dRoomRate { get; set; }
        public Nullable<decimal> dTaxes { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
