//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupM
    {
        public tblGroupM()
        {
            this.tblGroupMenuMs = new HashSet<tblGroupMenuM>();
            this.tblUserGroupMs = new HashSet<tblUserGroupM>();
        }
    
        public int iGroupId { get; set; }
        public string sGroupName { get; set; }
        public string sDescription { get; set; }
        public System.DateTime dtCreationDate { get; set; }
        public Nullable<int> iCreatedBy { get; set; }
        public string cStatus { get; set; }
        public System.DateTime dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblUserM tblUserM { get; set; }
        public virtual tblUserM tblUserM1 { get; set; }
        public virtual ICollection<tblGroupMenuM> tblGroupMenuMs { get; set; }
        public virtual ICollection<tblUserGroupM> tblUserGroupMs { get; set; }
    }
}
