//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelPartnerM
    {
        public int iID { get; set; }
        public string sHotelName { get; set; }
        public Nullable<byte> iStarCategory { get; set; }
        public string sWebsiteUrl { get; set; }
        public string sAddress { get; set; }
        public string sCity { get; set; }
        public string sState { get; set; }
        public string sCountry { get; set; }
        public string sPIN { get; set; }
        public string sBoardLineNumber { get; set; }
        public string sFirstName { get; set; }
        public string sLastName { get; set; }
        public string sDesignation { get; set; }
        public string sEmail { get; set; }
        public string sMobile { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
