//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelFacilitesRankM
    {
        public int iHoteFacilityId { get; set; }
        public string sHotelFacilites { get; set; }
        public Nullable<byte> iRank { get; set; }
        public string sImgUrl { get; set; }
    }
}
