//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndianLocalityCordinate
    {
        public tblIndianLocalityCordinate()
        {
            this.tblPolygons = new HashSet<tblPolygon>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GoogleFriendlyPlaceId { get; set; }
        public string LocalityName { get; set; }
        public string StateName { get; set; }
        public Nullable<int> LocalityId { get; set; }
    
        public virtual ICollection<tblPolygon> tblPolygons { get; set; }
    }
}
