//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookUp
    {
        public int iPropId { get; set; }
        public long iRoomId { get; set; }
        public int iRPPromoId { get; set; }
        public bool bIsPromo { get; set; }
        public System.DateTime dtStayDay { get; set; }
        public byte iOccupancy { get; set; }
        public Nullable<bool> b24HrsCheckIn { get; set; }
        public string sCheckInHH { get; set; }
        public string sCheckInMM { get; set; }
        public Nullable<byte> iExtraBedRequiredFrom { get; set; }
        public Nullable<decimal> dExtraBedCharges { get; set; }
        public Nullable<bool> bChildrenAllowed { get; set; }
        public Nullable<byte> iComplimentaryStayAge { get; set; }
        public Nullable<byte> iMaxOccupancy { get; set; }
        public Nullable<bool> bRoomActive { get; set; }
        public Nullable<short> iAvailableInventory { get; set; }
        public Nullable<bool> bStopSell { get; set; }
        public Nullable<short> iCutOff { get; set; }
        public Nullable<short> iMinLengthStayRP { get; set; }
        public Nullable<short> iMaxLengthStayRP { get; set; }
        public Nullable<short> dHrsDays { get; set; }
        public string cHrsDays { get; set; }
        public Nullable<bool> bIsBefore { get; set; }
        public Nullable<bool> bIsSecretDeal { get; set; }
        public string cRPPromoStatus { get; set; }
        public Nullable<bool> bParentActive { get; set; }
        public Nullable<bool> bCloseOut { get; set; }
        public Nullable<short> iMinLengthStay { get; set; }
        public Nullable<short> iMaxLengthStay { get; set; }
        public Nullable<bool> bCTA { get; set; }
        public Nullable<bool> bCTD { get; set; }
        public Nullable<decimal> dPrice { get; set; }
        public Nullable<System.DateTime> dtBookingStartDate { get; set; }
        public Nullable<System.DateTime> dtBookingEndDate { get; set; }
        public Nullable<byte> iNoOfExtraBedsUsed { get; set; }
        public Nullable<short> iHrsDaysPromo { get; set; }
        public string cHrsDaysPromo { get; set; }
        public Nullable<bool> bIsBeforePromo { get; set; }
        public Nullable<bool> bIsAirConditioning { get; set; }
        public Nullable<bool> bIsBathtub { get; set; }
        public Nullable<bool> bIsFlatScreenTV { get; set; }
        public Nullable<bool> bIsSoundproof { get; set; }
        public Nullable<bool> bIsView { get; set; }
        public Nullable<bool> bIsInternetFacilities { get; set; }
        public Nullable<bool> bIsPrivatePool { get; set; }
        public Nullable<bool> bIsRoomService { get; set; }
        public Nullable<byte> iPromoType { get; set; }
        public Nullable<decimal> dPriceRP { get; set; }
    }
}
