//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocalityM
    {
        public int iLocalityId { get; set; }
        public Nullable<int> iAreaId { get; set; }
        public Nullable<int> iCountryId { get; set; }
        public Nullable<int> iStateId { get; set; }
        public Nullable<int> iCityId { get; set; }
        public string sLocality { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblCityM tblCityM { get; set; }
        public virtual tblCountryM tblCountryM { get; set; }
        public virtual tblMacroAreaM tblMacroAreaM { get; set; }
        public virtual tblStateM tblStateM { get; set; }
    }
}
