//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocalitySearchM
    {
        public int iCityId { get; set; }
        public int iAreaId { get; set; }
        public int iLocalityId { get; set; }
        public string sLocality { get; set; }
        public string sArea { get; set; }
        public string sCity { get; set; }
    }
}
