//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuM
    {
        public tblMenuM()
        {
            this.tblGroupMenuMs = new HashSet<tblGroupMenuM>();
            this.tblMenuM1 = new HashSet<tblMenuM>();
        }
    
        public int iMenuId { get; set; }
        public Nullable<int> iParentId { get; set; }
        public string sMenuName { get; set; }
        public string sDescription { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public string cStatus { get; set; }
        public string sPath { get; set; }
        public Nullable<byte> iShownInMenu { get; set; }
        public short iDispSeq { get; set; }
        public Nullable<byte> iMenuType { get; set; }
    
        public virtual ICollection<tblGroupMenuM> tblGroupMenuMs { get; set; }
        public virtual ICollection<tblMenuM> tblMenuM1 { get; set; }
        public virtual tblMenuM tblMenuM2 { get; set; }
    }
}
