//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNegotiationActionRecord
    {
        public long iBookingId { get; set; }
        public int iPropId { get; set; }
        public string cType { get; set; }
        public System.DateTime dtActionDate { get; set; }
    }
}
