//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRoomMap_log
    {
        public long iRoomId { get; set; }
        public int iPropId { get; set; }
        public short iRoomTypeId { get; set; }
        public string sRoomName { get; set; }
        public string sRoomCode { get; set; }
        public Nullable<byte> iMaxOccupancy { get; set; }
        public Nullable<byte> iMaxChildren { get; set; }
        public Nullable<byte> iNoOfExtraBeds { get; set; }
        public Nullable<byte> iNoOfBedrooms { get; set; }
        public Nullable<byte> iNoOfBathrooms { get; set; }
        public Nullable<decimal> dSizeSqft { get; set; }
        public Nullable<decimal> dSizeMtr { get; set; }
        public string sSizeType { get; set; }
        public Nullable<short> iTotalRooms { get; set; }
        public Nullable<short> iTwinBeds { get; set; }
        public Nullable<short> iDoubleBeds { get; set; }
        public string sRoomAccessibilityIds { get; set; }
        public string sBuildingCharacteristicsIds { get; set; }
        public string sRoomOutdoorViewIds { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public bool bActive { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
        public Nullable<byte> iSeq { get; set; }
    }
}
