//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRoomAmentiesMap
    {
        public int iPropId { get; set; }
        public string sBasicRoomAmenities { get; set; }
        public string sAdditionalRoomAmenities { get; set; }
        public string sBathRoomAmenities { get; set; }
        public string sBeddingRoomAmenities { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<int> iBasicAmentiesRadio { get; set; }
    
        public virtual tblPropertyM tblPropertyM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
