//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyPromotionCancellationMainMap
    {
        public int iID { get; set; }
        public System.DateTime dtCancellationValidFrom { get; set; }
        public System.DateTime dtCancellationValidTo { get; set; }
        public string sCancellationPolicyId { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblPropertyPromotionMap tblPropertyPromotionMap { get; set; }
    }
}
