//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyPhotoMap
    {
        public tblPropertyPhotoMap()
        {
            this.tblPropertyPrimaryPhotoMaps = new HashSet<tblPropertyPrimaryPhotoMap>();
        }
    
        public long iPhotoId { get; set; }
        public int iPropId { get; set; }
        public Nullable<int> iPhotoCatId { get; set; }
        public Nullable<long> iPhotoSubCatId { get; set; }
        public Nullable<bool> bIsHighRes { get; set; }
        public Nullable<bool> bIsPrimaryH { get; set; }
        public Nullable<bool> bIsPrimaryR { get; set; }
        public string sImgUrl { get; set; }
        public Nullable<short> iResolutionW { get; set; }
        public Nullable<short> iResolutionH { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<bool> bIsMapped { get; set; }
        public string UniqueAzureFileName { get; set; }
    
        public virtual tblPhotoCategoryM tblPhotoCategoryM { get; set; }
        public virtual tblPropertyM tblPropertyM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblPropertyPrimaryPhotoMap> tblPropertyPrimaryPhotoMaps { get; set; }
    }
}
