//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyTripAdvisorAwardsM
    {
        public int iTripAdvisorLOCID { get; set; }
        public string sAwardType { get; set; }
        public string sDisplayName { get; set; }
        public Nullable<short> iYear { get; set; }
        public string sTinyImg { get; set; }
        public string sSmallImg { get; set; }
        public string sLargeImg { get; set; }
        public string sCategories { get; set; }
    }
}
