//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRatePlanMap_log
    {
        public int iRPId { get; set; }
        public Nullable<int> iPropId { get; set; }
        public string sRatePlan { get; set; }
        public string cRatePlanType { get; set; }
        public Nullable<System.DateTime> dtValidFrom { get; set; }
        public Nullable<System.DateTime> dtValidTo { get; set; }
        public Nullable<bool> bLinkToExistingRatePlan { get; set; }
        public Nullable<int> iLinkRatePlanId { get; set; }
        public Nullable<bool> bIsPlus { get; set; }
        public Nullable<bool> bIsPercent { get; set; }
        public Nullable<decimal> dValue { get; set; }
        public string sAmenityId { get; set; }
        public string sAmenity { get; set; }
        public Nullable<short> iMinLengthStay { get; set; }
        public Nullable<short> iMaxLengthStay { get; set; }
        public Nullable<short> dHrsDays { get; set; }
        public string cHrsDays { get; set; }
        public Nullable<bool> bIsBefore { get; set; }
        public string sCancellationPolicy { get; set; }
        public Nullable<System.DateTime> dtCancellationValidFrom { get; set; }
        public Nullable<System.DateTime> dtCancellationValidTo { get; set; }
        public Nullable<bool> bIsSecretDeal { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
        public string sRoomId { get; set; }
        public Nullable<decimal> dNegotiationPer { get; set; }
    }
}
