//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromoM
    {
        public tblPromoM()
        {
            this.tblPropertyPromotionMaps = new HashSet<tblPropertyPromotionMap>();
        }
    
        public int iPromoId { get; set; }
        public string sPromoName { get; set; }
    
        public virtual ICollection<tblPropertyPromotionMap> tblPropertyPromotionMaps { get; set; }
    }
}
