//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyReviewTG_Tmp
    {
        public long iPropertyReviewId { get; set; }
        public string iVendorId { get; set; }
        public string sAvgGuestRating { get; set; }
        public Nullable<short> iOverallRating { get; set; }
        public string sComments { get; set; }
        public Nullable<short> iRoomQuality { get; set; }
        public Nullable<short> iServiceQuality { get; set; }
        public Nullable<short> iDiningQuality { get; set; }
        public Nullable<short> iCleanliness { get; set; }
        public Nullable<System.DateTime> dtPost_Date { get; set; }
        public string sConsumer_city { get; set; }
        public string sConsumer_Country { get; set; }
        public string sCustomer_name { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
