//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyPolicyMap_log
    {
        public int iPropId { get; set; }
        public string sCreditCardId { get; set; }
        public Nullable<bool> b24HrsCheckIn { get; set; }
        public string sCheckInHH { get; set; }
        public string sCheckInMM { get; set; }
        public Nullable<bool> bEarlyCheckInChargeable { get; set; }
        public Nullable<bool> b24HrsCheckout { get; set; }
        public string sCheckoutHH { get; set; }
        public string sCheckoutMM { get; set; }
        public Nullable<bool> bEarlyCheckoutChargeable { get; set; }
        public Nullable<byte> iMinCheckInAge { get; set; }
        public bool bChildrenAllowed { get; set; }
        public Nullable<byte> iComplimentaryStayAge { get; set; }
        public Nullable<byte> iExtraBedRequiredFrom { get; set; }
        public Nullable<decimal> dExtraBedCharges { get; set; }
        public bool bAlcoholAllowedOnsite { get; set; }
        public bool bAlcoholServedOnsite { get; set; }
        public bool bVisitorsAllowed { get; set; }
        public bool bPetsAllowed { get; set; }
        public bool bPartiesAllowed { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
    }
}
