//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRoomRatePlanInventoryMap
    {
        public System.DateTime dtInventoryDate { get; set; }
        public int iPropId { get; set; }
        public long iRoomId { get; set; }
        public int iRPId { get; set; }
        public bool bCloseOut { get; set; }
        public Nullable<short> iMinLengthStay { get; set; }
        public Nullable<short> iMaxLengthStay { get; set; }
        public bool bCTA { get; set; }
        public bool bCTD { get; set; }
        public Nullable<decimal> dSingleRate { get; set; }
        public Nullable<decimal> dDoubleRate { get; set; }
        public Nullable<decimal> dTripleRate { get; set; }
        public Nullable<decimal> dQuadrupleRate { get; set; }
        public Nullable<decimal> dQuintrupleRate { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblPropertyM tblPropertyM { get; set; }
        public virtual tblPropertyRatePlanMap tblPropertyRatePlanMap { get; set; }
        public virtual tblPropertyRoomMap tblPropertyRoomMap { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
