//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyFacilityTG_Tmp
    {
        public long iPropertyFacilityId { get; set; }
        public Nullable<int> iAmenityId { get; set; }
        public string sAmenityType { get; set; }
        public string sDescription { get; set; }
        public string iVendorId { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
