//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyPhotoMap_log
    {
        public long iPhotoId { get; set; }
        public int iPropId { get; set; }
        public Nullable<int> iPhotoCatId { get; set; }
        public Nullable<long> iPhotoSubCatId { get; set; }
        public Nullable<bool> bIsHighRes { get; set; }
        public Nullable<bool> bIsPrimaryH { get; set; }
        public Nullable<bool> bIsPrimaryR { get; set; }
        public string sImgUrl { get; set; }
        public Nullable<short> iResolutionW { get; set; }
        public Nullable<short> iResolutionH { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<bool> bIsMapped { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
    }
}
