//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyTaxesMap
    {
        public int iID { get; set; }
        public int iPropTaxId { get; set; }
        public int iTaxId { get; set; }
        public Nullable<bool> bIsPercent { get; set; }
        public Nullable<decimal> dValue { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblPropertyTaxMap tblPropertyTaxMap { get; set; }
        public virtual tblTaxM tblTaxM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
