//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyPromotionMap
    {
        public tblPropertyPromotionMap()
        {
            this.tblPropertyPromoRateMaps = new HashSet<tblPropertyPromoRateMap>();
            this.tblPropertyPromotionCancellationMainMaps = new HashSet<tblPropertyPromotionCancellationMainMap>();
            this.tblPropertyPromotionCancellationMaps = new HashSet<tblPropertyPromotionCancellationMap>();
            this.tblPropertyPromotionRoomTypeMaps = new HashSet<tblPropertyPromotionRoomTypeMap>();
        }
    
        public int iID { get; set; }
        public int iPropId { get; set; }
        public int iPromoId { get; set; }
        public Nullable<System.DateTime> dtBookingDateFrom { get; set; }
        public Nullable<System.DateTime> dtBookingDateTo { get; set; }
        public Nullable<System.DateTime> dtStayDateFrom { get; set; }
        public Nullable<System.DateTime> dtStayDateTo { get; set; }
        public Nullable<int> iRPId { get; set; }
        public Nullable<bool> bIsPlus { get; set; }
        public Nullable<bool> bIsPercent { get; set; }
        public Nullable<decimal> dValue { get; set; }
        public string sRoomTypeId { get; set; }
        public string sAmenityId { get; set; }
        public string sAmenity { get; set; }
        public string sCancellationPolicy { get; set; }
        public Nullable<bool> bIsSecretDeal { get; set; }
        public Nullable<short> iHrsDays { get; set; }
        public Nullable<short> iMinLengthStay { get; set; }
        public Nullable<short> iMaxLengthStay { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string cStatus { get; set; }
        public Nullable<decimal> dNegotiationPer { get; set; }
        public Nullable<bool> bParentActive { get; set; }
    
        public virtual tblPromoM tblPromoM { get; set; }
        public virtual tblPropertyM tblPropertyM { get; set; }
        public virtual ICollection<tblPropertyPromoRateMap> tblPropertyPromoRateMaps { get; set; }
        public virtual ICollection<tblPropertyPromotionCancellationMainMap> tblPropertyPromotionCancellationMainMaps { get; set; }
        public virtual ICollection<tblPropertyPromotionCancellationMap> tblPropertyPromotionCancellationMaps { get; set; }
        public virtual tblPropertyRatePlanMap tblPropertyRatePlanMap { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblPropertyPromotionRoomTypeMap> tblPropertyPromotionRoomTypeMaps { get; set; }
    }
}
