//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyTripAdvisorM
    {
        public int iPropId { get; set; }
        public Nullable<int> iTripAdvisorLOCID { get; set; }
        public string sRatingImageURL { get; set; }
        public Nullable<decimal> iRating { get; set; }
        public string sRankingString { get; set; }
        public Nullable<int> iReviewsCount { get; set; }
        public string sWebURL { get; set; }
        public Nullable<int> iRanking { get; set; }
        public Nullable<decimal> iLocationRating { get; set; }
        public string sLocationRatingURL { get; set; }
        public Nullable<decimal> iSleepQualityRating { get; set; }
        public string sSleepQualityRatingURL { get; set; }
        public Nullable<decimal> iRoomsRating { get; set; }
        public string sRoomsRatingURL { get; set; }
        public Nullable<decimal> iServiceRating { get; set; }
        public string sServiceRatingURL { get; set; }
        public Nullable<decimal> iValueRating { get; set; }
        public string sValueRatingURL { get; set; }
        public Nullable<decimal> iCleanlinessRating { get; set; }
        public string sCleanlinessRatingURL { get; set; }
        public Nullable<long> review_rating1_count { get; set; }
        public Nullable<long> review_rating2_count { get; set; }
        public Nullable<long> review_rating3_count { get; set; }
        public Nullable<long> review_rating4_count { get; set; }
        public Nullable<long> review_rating5_count { get; set; }
        public string write_review { get; set; }
    }
}
