//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyTaxMap
    {
        public tblPropertyTaxMap()
        {
            this.tblPropertyTaxesMaps = new HashSet<tblPropertyTaxesMap>();
        }
    
        public int iPropTaxId { get; set; }
        public int iPropId { get; set; }
        public Nullable<int> iRPId { get; set; }
        public Nullable<long> iRoomId { get; set; }
        public Nullable<System.DateTime> dtStayFrom { get; set; }
        public Nullable<System.DateTime> dtStayTo { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblPropertyRoomMap tblPropertyRoomMap { get; set; }
        public virtual ICollection<tblPropertyTaxesMap> tblPropertyTaxesMaps { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
