//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyMTG_Tmp
    {
        public int iPropId { get; set; }
        public string sHotelName { get; set; }
        public string iChainId { get; set; }
        public Nullable<short> iStarCategoryId { get; set; }
        public Nullable<short> iCurrencyId { get; set; }
        public Nullable<int> iAccomodationId { get; set; }
        public Nullable<short> iYearBuilt { get; set; }
        public Nullable<short> iLastRenovation { get; set; }
        public Nullable<short> iRooms { get; set; }
        public Nullable<short> iFloors { get; set; }
        public Nullable<short> iTower { get; set; }
        public string sLocality { get; set; }
        public string sArea { get; set; }
        public string sAddress { get; set; }
        public string sCountry { get; set; }
        public string sState { get; set; }
        public string sCity { get; set; }
        public Nullable<int> iPinCode { get; set; }
        public string sWebSite { get; set; }
        public Nullable<decimal> dLatitude { get; set; }
        public Nullable<decimal> dLongitude { get; set; }
        public string sDescription { get; set; }
        public string sDistanceFromAirportRailwayStation { get; set; }
        public string sNearestTransport { get; set; }
        public string sAreaRecommended { get; set; }
        public string sTopAttractions { get; set; }
        public string sGeneralManagerName { get; set; }
        public string sRevenueManagerName { get; set; }
        public string sFinanceContactName { get; set; }
        public string sPrimaryContactName { get; set; }
        public string sGeneralManagerContact { get; set; }
        public string sRevenueManagerContact { get; set; }
        public string sFinanceContactContact { get; set; }
        public string sPrimaryContactContact { get; set; }
        public string sGeneralManagerEmail { get; set; }
        public string sRevenueManagerEmail { get; set; }
        public string sFinanceContactEmail { get; set; }
        public string sPrimaryContactEmail { get; set; }
        public string sAccessbilityIds { get; set; }
        public string sAwardIds { get; set; }
        public string sAffiliationIds { get; set; }
        public string sLanguageIds { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sAreaRecommended1 { get; set; }
        public string sAreaRecommended2 { get; set; }
        public string sAreaRecommended3 { get; set; }
        public string sNearestTransport1 { get; set; }
        public Nullable<decimal> dNearestTransport1 { get; set; }
        public string sNearestTransport2 { get; set; }
        public Nullable<decimal> dNearestTransport2 { get; set; }
        public string sNearestTransport3 { get; set; }
        public Nullable<decimal> dNearestTransport3 { get; set; }
        public string sTopAttraction1 { get; set; }
        public string sTopAttraction2 { get; set; }
        public string sTopAttraction3 { get; set; }
        public string sDistanceToAirportRailway1 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway1 { get; set; }
        public string sDistanceToAirportRailway2 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway2 { get; set; }
        public string sDistanceToAirportRailway3 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway3 { get; set; }
        public string sConfirmationContactName { get; set; }
        public string sConfirmationContactEmail { get; set; }
        public string sConfirmationContactContact { get; set; }
        public string iVendorId { get; set; }
        public Nullable<bool> bIsTG { get; set; }
        public string sImageUrlTG { get; set; }
        public string sSecondaryAreaNameTG { get; set; }
    }
}
