//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRoomInventory_log
    {
        public System.DateTime dtInventoryDate { get; set; }
        public int iPropId { get; set; }
        public long iRoomId { get; set; }
        public Nullable<short> iInventory { get; set; }
        public Nullable<short> iSoldInventory { get; set; }
        public Nullable<short> iAvailableInventory { get; set; }
        public bool bStopSell { get; set; }
        public Nullable<short> iCutOff { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
    }
}
