//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyBasicBiddingMapCorp
    {
        public int iPropId { get; set; }
        public System.DateTime dtEffectiveDate { get; set; }
        public Nullable<bool> bIsClosed { get; set; }
        public Nullable<bool> bCTA { get; set; }
        public Nullable<bool> bCTD { get; set; }
        public Nullable<decimal> dBasicDiscount { get; set; }
        public Nullable<bool> bIsClosedroom { get; set; }
        public Nullable<bool> bCTAroom { get; set; }
        public Nullable<bool> bCTDroom { get; set; }
        public Nullable<bool> bIsClosedlead { get; set; }
        public Nullable<bool> bCTAlead { get; set; }
        public Nullable<bool> bCTDlead { get; set; }
        public Nullable<bool> bIsClosedlos { get; set; }
        public Nullable<bool> bCTAlos { get; set; }
        public Nullable<bool> bCTDlos { get; set; }
        public Nullable<bool> bIsClosedweek { get; set; }
        public Nullable<bool> bCTAweek { get; set; }
        public Nullable<bool> bCTDweek { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblUserM tblUserM { get; set; }
    }
}
