//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyAmenitiesMap
    {
        public int iPropId { get; set; }
        public string sHotelAmenities { get; set; }
        public string sHotelParkings { get; set; }
        public string sHotelCommonServices { get; set; }
        public string sHotelConvenience { get; set; }
        public string sHotelLeisure { get; set; }
        public string sHotelMeetings { get; set; }
        public bool bAirportTransferAvalible { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sHotelParkingRadio { get; set; }
    
        public virtual tblPropertyM tblPropertyM { get; set; }
    }
}
