//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyBidUpgradeM
    {
        public int iPropId { get; set; }
        public System.DateTime dtEffectiveDate { get; set; }
        public long iRoomId { get; set; }
        public Nullable<decimal> dUpgradeCharge { get; set; }
        public string sUpgradeType { get; set; }
        public Nullable<bool> bCloseOut { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    }
}
