//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhotoCategoryM
    {
        public tblPhotoCategoryM()
        {
            this.tblPhotoSubCategoryMs = new HashSet<tblPhotoSubCategoryM>();
            this.tblPropertyPhotoMaps = new HashSet<tblPropertyPhotoMap>();
        }
    
        public int iPhotoCatId { get; set; }
        public string sPhotoCatName { get; set; }
    
        public virtual ICollection<tblPhotoSubCategoryM> tblPhotoSubCategoryMs { get; set; }
        public virtual ICollection<tblPropertyPhotoMap> tblPropertyPhotoMaps { get; set; }
    }
}
