//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyTopAttrationTG_Tmp
    {
        public long iPropertyTopAttractionId { get; set; }
        public string iVendorId { get; set; }
        public string sNameOfAttraction { get; set; }
        public Nullable<decimal> iDistanceInKM { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
