//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyRatePlanMap
    {
        public tblPropertyRatePlanMap()
        {
            this.tblChangeHistoryRates = new HashSet<tblChangeHistoryRate>();
            this.tblPropertyBiddingRateMs = new HashSet<tblPropertyBiddingRateM>();
            this.tblPropertyPromotionMaps = new HashSet<tblPropertyPromotionMap>();
            this.tblPropertyRatePlanRoomTypeMaps = new HashSet<tblPropertyRatePlanRoomTypeMap>();
            this.tblPropertyRoomRatePlanInventoryMaps = new HashSet<tblPropertyRoomRatePlanInventoryMap>();
        }
    
        public int iRPId { get; set; }
        public Nullable<int> iPropId { get; set; }
        public string sRatePlan { get; set; }
        public string cRatePlanType { get; set; }
        public Nullable<System.DateTime> dtValidFrom { get; set; }
        public Nullable<System.DateTime> dtValidTo { get; set; }
        public Nullable<bool> bLinkToExistingRatePlan { get; set; }
        public Nullable<int> iLinkRatePlanId { get; set; }
        public Nullable<bool> bIsPlus { get; set; }
        public Nullable<bool> bIsPercent { get; set; }
        public Nullable<decimal> dValue { get; set; }
        public string sAmenityId { get; set; }
        public string sAmenity { get; set; }
        public Nullable<short> iMinLengthStay { get; set; }
        public Nullable<short> iMaxLengthStay { get; set; }
        public Nullable<short> dHrsDays { get; set; }
        public string cHrsDays { get; set; }
        public Nullable<bool> bIsBefore { get; set; }
        public string sCancellationPolicy { get; set; }
        public Nullable<System.DateTime> dtCancellationValidFrom { get; set; }
        public Nullable<System.DateTime> dtCancellationValidTo { get; set; }
        public Nullable<bool> bIsSecretDeal { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sRoomId { get; set; }
        public Nullable<decimal> dNegotiationPer { get; set; }
        public Nullable<bool> bParentActive { get; set; }
    
        public virtual ICollection<tblChangeHistoryRate> tblChangeHistoryRates { get; set; }
        public virtual ICollection<tblPropertyBiddingRateM> tblPropertyBiddingRateMs { get; set; }
        public virtual ICollection<tblPropertyPromotionMap> tblPropertyPromotionMaps { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblPropertyRatePlanRoomTypeMap> tblPropertyRatePlanRoomTypeMaps { get; set; }
        public virtual ICollection<tblPropertyRoomRatePlanInventoryMap> tblPropertyRoomRatePlanInventoryMaps { get; set; }
    }
}
