//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyM
    {
        public tblPropertyM()
        {
            this.tblAdditionalCommisions = new HashSet<tblAdditionalCommision>();
            this.tblChangeHistoryPIRooms = new HashSet<tblChangeHistoryPIRoom>();
            this.tblChangeHistoryRates = new HashSet<tblChangeHistoryRate>();
            this.tblChangeHistoryRooms = new HashSet<tblChangeHistoryRoom>();
            this.tblChannelMgrBookingTxes = new HashSet<tblChannelMgrBookingTx>();
            this.tblMyWishListTxes = new HashSet<tblMyWishListTx>();
            this.tblPropertyBasicBiddingMaps = new HashSet<tblPropertyBasicBiddingMap>();
            this.tblPropertyBiddingRateMs = new HashSet<tblPropertyBiddingRateM>();
            this.tblPropertyLeadTimeBiddingMaps = new HashSet<tblPropertyLeadTimeBiddingMap>();
            this.tblPropertyLeadTimeBiddingMapCorps = new HashSet<tblPropertyLeadTimeBiddingMapCorp>();
            this.tblPropertyLOSBiddingMaps = new HashSet<tblPropertyLOSBiddingMap>();
            this.tblPropertyLOSBiddingMapCorps = new HashSet<tblPropertyLOSBiddingMapCorp>();
            this.tblPropertyWeekendBiddingMaps = new HashSet<tblPropertyWeekendBiddingMap>();
            this.tblPropertyWeekendBiddingMapCorps = new HashSet<tblPropertyWeekendBiddingMapCorp>();
            this.tblPropertyParkingMaps = new HashSet<tblPropertyParkingMap>();
            this.tblPropertyPhotoMaps = new HashSet<tblPropertyPhotoMap>();
            this.tblPropertyPrimaryPhotoMaps = new HashSet<tblPropertyPrimaryPhotoMap>();
            this.tblPropertyPromoMaps = new HashSet<tblPropertyPromoMap>();
            this.tblPropertyPromotionMaps = new HashSet<tblPropertyPromotionMap>();
            this.tblPropertyRoomInventories = new HashSet<tblPropertyRoomInventory>();
            this.tblPropertyRoomRatePlanInventoryMaps = new HashSet<tblPropertyRoomRatePlanInventoryMap>();
            this.tblPropertyRoomsBiddingMaps = new HashSet<tblPropertyRoomsBiddingMap>();
            this.tblPropertyRoomsBiddingMapCorps = new HashSet<tblPropertyRoomsBiddingMapCorp>();
            this.tblPropertyRoomTypeRoomAmentiesMaps = new HashSet<tblPropertyRoomTypeRoomAmentiesMap>();
            this.tblRecentViewsTxes = new HashSet<tblRecentViewsTx>();
            this.tblUserPropertyMaps = new HashSet<tblUserPropertyMap>();
            this.tblViewForConversions = new HashSet<tblViewForConversion>();
        }
    
        public int iPropId { get; set; }
        public string sHotelName { get; set; }
        public Nullable<int> iChainId { get; set; }
        public Nullable<short> iStarCategoryId { get; set; }
        public Nullable<short> iCurrencyId { get; set; }
        public Nullable<int> iAccomodationId { get; set; }
        public Nullable<short> iYearBuilt { get; set; }
        public Nullable<short> iLastRenovation { get; set; }
        public Nullable<short> iRooms { get; set; }
        public Nullable<byte> iFloors { get; set; }
        public Nullable<byte> iTower { get; set; }
        public Nullable<int> iLocalityId { get; set; }
        public Nullable<int> iAreaId { get; set; }
        public string sAddress { get; set; }
        public int iCountryId { get; set; }
        public int iStateId { get; set; }
        public int iCityId { get; set; }
        public Nullable<int> iPinCode { get; set; }
        public string sWebSite { get; set; }
        public Nullable<decimal> dLatitude { get; set; }
        public Nullable<decimal> dLongitude { get; set; }
        public string sDescription { get; set; }
        public string sDistanceFromAirportRailwayStation { get; set; }
        public string sNearestTransport { get; set; }
        public string sAreaRecommended { get; set; }
        public string sTopAttractions { get; set; }
        public string sGeneralManagerName { get; set; }
        public string sRevenueManagerName { get; set; }
        public string sFinanceContactName { get; set; }
        public string sPrimaryContactName { get; set; }
        public string sGeneralManagerContact { get; set; }
        public string sRevenueManagerContact { get; set; }
        public string sFinanceContactContact { get; set; }
        public string sPrimaryContactContact { get; set; }
        public string sGeneralManagerEmail { get; set; }
        public string sRevenueManagerEmail { get; set; }
        public string sFinanceContactEmail { get; set; }
        public string sPrimaryContactEmail { get; set; }
        public string sAccessbilityIds { get; set; }
        public string sAwardIds { get; set; }
        public string sAffiliationIds { get; set; }
        public string sLanguageIds { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sAreaRecommended1 { get; set; }
        public string sAreaRecommended2 { get; set; }
        public string sAreaRecommended3 { get; set; }
        public string sNearestTransport1 { get; set; }
        public Nullable<decimal> dNearestTransport1 { get; set; }
        public string sNearestTransport2 { get; set; }
        public Nullable<decimal> dNearestTransport2 { get; set; }
        public string sNearestTransport3 { get; set; }
        public Nullable<decimal> dNearestTransport3 { get; set; }
        public string sTopAttraction1 { get; set; }
        public string sTopAttraction2 { get; set; }
        public string sTopAttraction3 { get; set; }
        public string sDistanceToAirportRailway1 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway1 { get; set; }
        public string sDistanceToAirportRailway2 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway2 { get; set; }
        public string sDistanceToAirportRailway3 { get; set; }
        public Nullable<decimal> dDistanceToAirportRailway3 { get; set; }
        public string sConfirmationContactName { get; set; }
        public string sConfirmationContactEmail { get; set; }
        public string sConfirmationContactContact { get; set; }
        public string iVendorId { get; set; }
        public Nullable<bool> bIsTG { get; set; }
        public string rating_image_url { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string ranking_string { get; set; }
        public string sImageUrlTG { get; set; }
        public string sSecondaryAreaNameTG { get; set; }
        public Nullable<decimal> dMinIncome { get; set; }
        public Nullable<System.DateTime> dtMinIncomeActionDate { get; set; }
        public Nullable<int> iMinIncomeActionBy { get; set; }
    
        public virtual tblAccomodationM tblAccomodationM { get; set; }
        public virtual ICollection<tblAdditionalCommision> tblAdditionalCommisions { get; set; }
        public virtual ICollection<tblChangeHistoryPIRoom> tblChangeHistoryPIRooms { get; set; }
        public virtual ICollection<tblChangeHistoryRate> tblChangeHistoryRates { get; set; }
        public virtual ICollection<tblChangeHistoryRoom> tblChangeHistoryRooms { get; set; }
        public virtual ICollection<tblChannelMgrBookingTx> tblChannelMgrBookingTxes { get; set; }
        public virtual tblCurrencyM tblCurrencyM { get; set; }
        public virtual ICollection<tblMyWishListTx> tblMyWishListTxes { get; set; }
        public virtual tblOFRPropertyM tblOFRPropertyM { get; set; }
        public virtual tblPropertyAmenitiesMap tblPropertyAmenitiesMap { get; set; }
        public virtual ICollection<tblPropertyBasicBiddingMap> tblPropertyBasicBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyBiddingRateM> tblPropertyBiddingRateMs { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMap> tblPropertyLeadTimeBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyLeadTimeBiddingMapCorp> tblPropertyLeadTimeBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMap> tblPropertyLOSBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyLOSBiddingMapCorp> tblPropertyLOSBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyWeekendBiddingMap> tblPropertyWeekendBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyWeekendBiddingMapCorp> tblPropertyWeekendBiddingMapCorps { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual ICollection<tblPropertyParkingMap> tblPropertyParkingMaps { get; set; }
        public virtual ICollection<tblPropertyPhotoMap> tblPropertyPhotoMaps { get; set; }
        public virtual tblPropertyPolicyMap tblPropertyPolicyMap { get; set; }
        public virtual ICollection<tblPropertyPrimaryPhotoMap> tblPropertyPrimaryPhotoMaps { get; set; }
        public virtual ICollection<tblPropertyPromoMap> tblPropertyPromoMaps { get; set; }
        public virtual ICollection<tblPropertyPromotionMap> tblPropertyPromotionMaps { get; set; }
        public virtual tblPropertyRoomAmentiesMap tblPropertyRoomAmentiesMap { get; set; }
        public virtual ICollection<tblPropertyRoomInventory> tblPropertyRoomInventories { get; set; }
        public virtual ICollection<tblPropertyRoomRatePlanInventoryMap> tblPropertyRoomRatePlanInventoryMaps { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMap> tblPropertyRoomsBiddingMaps { get; set; }
        public virtual ICollection<tblPropertyRoomsBiddingMapCorp> tblPropertyRoomsBiddingMapCorps { get; set; }
        public virtual ICollection<tblPropertyRoomTypeRoomAmentiesMap> tblPropertyRoomTypeRoomAmentiesMaps { get; set; }
        public virtual ICollection<tblRecentViewsTx> tblRecentViewsTxes { get; set; }
        public virtual ICollection<tblUserPropertyMap> tblUserPropertyMaps { get; set; }
        public virtual ICollection<tblViewForConversion> tblViewForConversions { get; set; }
    }
}
