//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoomRateRangeM
    {
        public tblRoomRateRangeM()
        {
            this.tblMasterTaxes = new HashSet<tblMasterTax>();
        }
    
        public int iRangeId { get; set; }
        public Nullable<int> dAmountFrom { get; set; }
        public Nullable<int> dAmountTo { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual ICollection<tblMasterTax> tblMasterTaxes { get; set; }
    }
}
