//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecentSavingsTx
    {
        public long iBookingId { get; set; }
        public string sCity { get; set; }
        public Nullable<short> iStar { get; set; }
        public string sSymbol { get; set; }
        public string sCurrencyCode { get; set; }
        public Nullable<decimal> dActualAmt { get; set; }
        public Nullable<decimal> dDiscountedAmt { get; set; }
        public Nullable<System.DateTime> dtBookingDate { get; set; }
    
        public virtual tblBookingTx tblBookingTx { get; set; }
    }
}
