//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRankManagement
    {
        public int iID { get; set; }
        public int iPropId { get; set; }
        public System.DateTime dtStartdate { get; set; }
        public System.DateTime dtEndDate { get; set; }
        public Nullable<bool> IsSponsored { get; set; }
        public Nullable<bool> IsRateDisparity { get; set; }
        public Nullable<int> iNewRank { get; set; }
        public Nullable<int> iOldRank { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    }
}
