//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoomTypeTGSearch_Tmp
    {
        public long iId { get; set; }
        public string sSessionId { get; set; }
        public string sHotelCode { get; set; }
        public string sRoomTypeCode { get; set; }
        public string sRoomType { get; set; }
        public string sNonSmoking { get; set; }
        public Nullable<int> iMinChildAge { get; set; }
        public Nullable<int> iMaxChildAge { get; set; }
        public Nullable<int> iMaxGuest { get; set; }
        public Nullable<int> iMaxChild { get; set; }
        public Nullable<int> iMaxAdult { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
