//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatePlanCancelPenaltyTGSpecific_Tmp
    {
        public long iId { get; set; }
        public string sSessionId { get; set; }
        public string sHotelCode { get; set; }
        public string sRatePlanCode { get; set; }
        public string sOffSetDropTime { get; set; }
        public string sOffSetTimeUnit { get; set; }
        public string sOffSetUnitMultiply { get; set; }
        public string sNumberOfNight { get; set; }
        public string sTaxInclusive { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
