//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatePlanTGSearch_Tmp
    {
        public long iId { get; set; }
        public string sSessionId { get; set; }
        public string sHotelCode { get; set; }
        public string sRatePlanType { get; set; }
        public string sRatePlanName { get; set; }
        public string sRatePlanCode { get; set; }
        public Nullable<int> iAvailableQuantity { get; set; }
        public string sRatePlanInclusion { get; set; }
        public string sDiscountCouponEnable { get; set; }
        public string sRatePlanDesc { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    }
}
