//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceChargeM_log
    {
        public int iServiceChargeId { get; set; }
        public Nullable<System.DateTime> dtFrom { get; set; }
        public Nullable<System.DateTime> dtTo { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public int iActionBy { get; set; }
        public decimal dServiceCharge { get; set; }
        public string cGstValueType { get; set; }
        public decimal dGstValue { get; set; }
        public string vc_changed_by { get; set; }
        public string vc_changed_ip { get; set; }
        public string vc_programname { get; set; }
        public Nullable<System.DateTime> dt_changed_date { get; set; }
        public string ch_action { get; set; }
    }
}
