//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTripAdvisorReview
    {
        public int iTripAdvisorLOCID { get; set; }
        public int iReviewId { get; set; }
        public string sTitle { get; set; }
        public string sText { get; set; }
        public string sReviewer { get; set; }
        public Nullable<decimal> iRating { get; set; }
        public string sRatingImageURL { get; set; }
        public string sReviewURL { get; set; }
        public Nullable<System.DateTime> dtReviewDate { get; set; }
        public Nullable<System.DateTime> dtTravelDate { get; set; }
        public string sTripType { get; set; }
        public string sUserLocation { get; set; }
        public Nullable<bool> bIsJointlyCollected { get; set; }
    }
}
