//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTGAmenitiesMap
    {
        public string iVendorId { get; set; }
        public Nullable<bool> H_Int { get; set; }
        public Nullable<bool> H_Park { get; set; }
        public Nullable<bool> H_Smoke { get; set; }
        public Nullable<bool> H_Disable { get; set; }
        public Nullable<bool> H_Fitness { get; set; }
        public Nullable<bool> H_Family { get; set; }
        public Nullable<bool> H_Restaurant { get; set; }
        public Nullable<bool> H_RoomServ { get; set; }
        public Nullable<bool> H_Transfer { get; set; }
        public Nullable<bool> H_Pets { get; set; }
        public Nullable<bool> H_Spa { get; set; }
        public Nullable<bool> H_OutDoorPool { get; set; }
        public Nullable<bool> H_InDoorPool { get; set; }
        public Nullable<bool> H_ChildCare { get; set; }
        public Nullable<bool> H_KidsClub { get; set; }
        public Nullable<bool> H_Laundary { get; set; }
        public Nullable<bool> H_AC { get; set; }
        public Nullable<bool> R_AC { get; set; }
        public Nullable<bool> R_Tub { get; set; }
        public Nullable<bool> R_TV { get; set; }
        public Nullable<bool> R_Sound { get; set; }
        public Nullable<bool> R_View { get; set; }
        public Nullable<bool> R_Pool { get; set; }
        public Nullable<bool> R_Int { get; set; }
        public Nullable<bool> R_RoomServ { get; set; }
    }
}
