//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxChangeForBookingTx
    {
        public long iId { get; set; }
        public Nullable<int> iBookingID { get; set; }
        public Nullable<bool> bEmailSent { get; set; }
        public Nullable<System.DateTime> dtEmailSentOn { get; set; }
        public string sEmail { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<decimal> dTaxOld { get; set; }
        public Nullable<decimal> dTaxNew { get; set; }
    }
}
