//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxM
    {
        public tblTaxM()
        {
            this.tblPropertyTaxesMaps = new HashSet<tblPropertyTaxesMap>();
            this.tblMasterTaxMaps = new HashSet<tblMasterTaxMap>();
        }
    
        public int iTaxId { get; set; }
        public string sTaxName { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual ICollection<tblPropertyTaxesMap> tblPropertyTaxesMaps { get; set; }
        public virtual ICollection<tblMasterTaxMap> tblMasterTaxMaps { get; set; }
        public virtual tblUserM tblUserM { get; set; }
    }
}
