//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroupM
    {
        public int iUserId { get; set; }
        public int iGroupId { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<int> iCreatedBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string cStatus { get; set; }
    
        public virtual tblGroupM tblGroupM { get; set; }
        public virtual tblUserM tblUserM { get; set; }
        public virtual tblUserM tblUserM1 { get; set; }
        public virtual tblUserM tblUserM2 { get; set; }
    }
}
