//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebsiteGuestUserMaster
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string sCountryPhoneCode { get; set; }
        public string GstnEntityType { get; set; }
        public string GstnNumber { get; set; }
        public string GstnEntityName { get; set; }
        public Nullable<int> iStateId { get; set; }
    }
}
