//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneFineRate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebsiteUserMater
    {
        public tblWebsiteUserMater()
        {
            this.tblBookingAmedTxes = new HashSet<tblBookingAmedTx>();
            this.tblBookingTxes = new HashSet<tblBookingTx>();
            this.tblCustomerLoyaltyBookingsMaps = new HashSet<tblCustomerLoyaltyBookingsMap>();
            this.tblCustomerPointsMaps = new HashSet<tblCustomerPointsMap>();
            this.tblMyWishListTxes = new HashSet<tblMyWishListTx>();
            this.tblWebsiteUserClaims = new HashSet<tblWebsiteUserClaim>();
            this.tblWebsiteUserLogins = new HashSet<tblWebsiteUserLogin>();
            this.tblRecentViewsTxes = new HashSet<tblRecentViewsTx>();
            this.tblWebsiteUserRoleMasters = new HashSet<tblWebsiteUserRoleMaster>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CorporateEmail { get; set; }
        public string CorporateEmailTemp { get; set; }
        public bool CorporateEmailConfirmed { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string MartialStatus { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string SpouseName { get; set; }
        public string ProfileImageUrl { get; set; }
        public string CurrentAddressLine1 { get; set; }
        public string CurrentAddressLine2 { get; set; }
        public string CurrentAddressLine3 { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string City { get; set; }
        public string ID_Type { get; set; }
        public string ID_Number { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string GovApprovedPhotoIdUrl { get; set; }
        public string SmokingRoom { get; set; }
        public string PreferedStarRating { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<bool> NewsNotifications { get; set; }
        public Nullable<bool> Facilities_For_Disabled_Guest { get; set; }
        public Nullable<bool> Fitness_Center { get; set; }
        public Nullable<bool> Internet_Services { get; set; }
        public Nullable<bool> Pets_Allowed { get; set; }
        public Nullable<bool> Luggage_Storage { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Front_Desk_24_Hour { get; set; }
        public Nullable<bool> Restaurant { get; set; }
        public Nullable<bool> Spa_And_Wellness_Center { get; set; }
        public Nullable<bool> Bar { get; set; }
        public Nullable<bool> Family_Rooms { get; set; }
        public Nullable<bool> Airport_Suttle { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<long> OFRPoints { get; set; }
        public string sReferralCode { get; set; }
        public string sCountryPhoneCode { get; set; }
        public string GstnEntityType { get; set; }
        public string GstnNumber { get; set; }
        public string GstnEntityName { get; set; }
    
        public virtual ICollection<tblBookingAmedTx> tblBookingAmedTxes { get; set; }
        public virtual ICollection<tblBookingTx> tblBookingTxes { get; set; }
        public virtual ICollection<tblCustomerLoyaltyBookingsMap> tblCustomerLoyaltyBookingsMaps { get; set; }
        public virtual ICollection<tblCustomerPointsMap> tblCustomerPointsMaps { get; set; }
        public virtual ICollection<tblMyWishListTx> tblMyWishListTxes { get; set; }
        public virtual ICollection<tblWebsiteUserClaim> tblWebsiteUserClaims { get; set; }
        public virtual ICollection<tblWebsiteUserLogin> tblWebsiteUserLogins { get; set; }
        public virtual ICollection<tblRecentViewsTx> tblRecentViewsTxes { get; set; }
        public virtual ICollection<tblWebsiteUserRoleMaster> tblWebsiteUserRoleMasters { get; set; }
    }
}
